### ISSUE TITLE
Command "git diff {branch}...HEAD" fails (master fetch doesn't help)

### ISSUE THREAD

**Issue by twall** [Bachmann1234/diff-cover#55]
Jenkins SCM module does the following (minimal representation, it actually does a few more things):

    git checkout git@github.com:<path>.git <dir>
    cd <dir>
    git checkout -f <commit-hash>

If I invoke `git diff {branch}...HEAD` (as is done by diff-cover), I get the same error as is produced when running diff-cover:
```fatal: ambiguous argument '{branch}...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'```

**Comment by Bachmann1234** [comment]
Howdy stranger!

I'll see if I can take a look at this. But as I've been saying in other things that have come up my free time has dried up dramatically recently so it may be a bit. We can talk in a less public forum if your curious.

But yeah, I'll try and look this week. No promises though

**Comment by Bachmann1234** [comment]
Hey, So the issue title makes me think you read the troubleshooting but I wanted to be extra sure.

When you say 'fetch master did not help' did you specifically make sure to try

`git fetch origin master:refs/remotes/origin/master` from the readme?

**Comment by twall** [comment]
No, I tried the troubleshooting tip, but it didn't work.  

An explicit checkout of the target branch (`master`) then switching back works, so I'm trying to figure out what happens differently in that case w/r/t symbolic references.

**Comment by f18m** [comment]
Hi @twall , @Bachmann1234 ,
I think I hit a similar problem. In my case I'm not using Jenkins but rather Teamcity. Also Teamcity does something like "git checkout -f <commit-hash>" at some point and thus clones the git repo in a "HEAD detached" condition (https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit/). 
I tried and indeed a command like "git diff origin/develop..HEAD" in such condition fails with error

`
fatal: ambiguous argument 'origin/develop..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
`

I'm not sure how to workaround this... any solution or workaround so far ?

**Comment by altendky** [comment]
For what it's worth...  This didn't work.

```yaml
    - name: Make ${{ github.base_ref }} branch exist
      run: |
        git fetch origin master:refs/remotes/origin/master
```
```
diff_cover.command_runner.CommandError: fatal: ambiguous argument 'master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

But this did.

```yaml
    - name: Make ${{ github.base_ref }} branch exist
      run: |
        git checkout -b ${{ github.base_ref }} --track origin/${{ github.base_ref }}
        git checkout -
```

Though now I'm just passing in the `origin/master` or the parent hash depending.  (isn't choosing either this or that just silly in GHA...)

```yaml
    - name: Run tox environment
      env:
        BASE_REF: ${{ fromJSON(format('[{0}, {1}]', toJSON(github.event.before), toJSON(format('origin/{0}', github.base_ref))))[github.base_ref != ''] }}
      run: |
        tox --skip-pkg-install -- --compare-branch="${BASE_REF}"
```

```ini
[testenv:check-coverage]
changedir = {toxinidir}
commands =
    coverage combine coverage_reports/
    coverage xml -o {toxinidir}/coverage.xml
    coverage report --fail-under=90 --ignore-errors
    diff-cover --fail-under=100 {posargs:--compare-branch=master} coverage.xml
```

https://github.com/Parquery/pylddwrap/pull/20

**Comment by dmcconnell-m** [comment]
I was able to get this to work in GitHub Actions by doing 2 separate checkouts in my workflow (1 for master / main first, then the branch / ref that triggered the workflow, my PR branch in my case):

```
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install diff_cover
        run: |
          python -m pip install --upgrade pip
          pip install diff_cover
     - run: diff-cover coverage.xml --compare-branch=origin/master --diff-range-notation '..'
```
I have added this in case anyone else is trying to get diff_cover working with GitHub Actions

**Comment by justasm** [comment]
@f18m for TeamCity specifically, I recently ran into this issue and discovered [this solution](https://stackoverflow.com/a/43997171) — adding the configuration parameter `teamcity.git.fetchAllHeads=true` fetches all branches as part of the standard VCS checkout.

**Comment by noamkush** [comment]
For anyone coming here, the solution by @dmcconnell-m didn't work for me so this is what I ended up using
``` yaml
    env:
      BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: GitHub bug workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Setup local base branch
        run: |
          git fetch origin $BASE_REF
          git branch $BASE_REF origin/$BASE_REF
      - run: diff-quality <...>
```
